/**
 * Twenty'em WordPress Framework.
 *
 * WARNING: This file is part of Twenty'em WordPress Framework.
 * DO NOT edit this file under any circumstances. Do all your modifications in the form of a child theme.
 *
 * @package			WordPress
 * @subpackage		Twenty'em
 * @author			RogerTM
 * @license			license.txt
 * @link			https://themingisprose.com/twenty-em
 * @since 			Twenty'em 1.2
 */

 /**
  * JavaScripts for Twenty'em WordPress Framework
  */
jQuery(document).ready(function($){
	// Bootstrap Tabs
	if ( $().tab ){
		$('.tabbable .tab-pane.active').addClass('show');
	}
});
