jQuery(document).ready(function($){
	$('#navigation-toggle').click(function(){
		$('#site-navigation').slideToggle('fast');
	});
	$('#top-toggle').click(function(){
		$('#top').slideToggle('fast');
	});
	$('#footer-toggle').click(function(){
		$('#footer-menu').slideToggle('fast');
	});
})
