<?php
/**
 * WARNING: Do not edit this files.
 * Load the theme functions files
 */
require( get_template_directory() . '/inc/functions.php' );
require( get_template_directory() . '/inc/enqueue.php' );
require( get_template_directory() . '/inc/version.php' );
require( get_template_directory() . '/inc/theme-options.php' );
require( get_template_directory() . '/inc/widgets.php' );
?>
