/**
 * Twenty'em WordPress Framework.
 *
 * WARNING: This file is part of Twenty'em WordPress Framework.
 * DO NOT edit this file under any circumstances. Do all your modifications in the form of a child theme.
 *
 * @package			WordPress
 * @subpackage		Twenty'em
 * @author			RogerTM
 * @license			license.txt
 * @link			https://themingisprose.com/twenty-em
 * @since 			Twenty'em 1.4
 */

const { gulp, dest, src, series, watch, task } = require('gulp');
const uglify			= require('gulp-uglify');
const rename			= require('gulp-rename');
const sass				= require('gulp-sass');
const cssClean			= require('gulp-clean-css');
const gulpCopy 			= require('gulp-copy');

var	jsSrc				= 'assets/src/js/',
	scssSrc				= 'assets/src/scss/',
	jsDist				= 'assets/dist/js/',
	cssDist				= 'assets/dist/css/',
	bootstrapSrc		= 'node_modules/bootstrap/**/*',
	iconPackSrc			= 'node_modules/@themingisprose/icon-pack/**/*',
	countDownTimerSrc	= 'node_modules/countdowntimer/**/*',
	jquerySrc			= 'node_modules/jquery/**/*',
	vendorsSrc			= [ bootstrapSrc, iconPackSrc, countDownTimerSrc, jquerySrc ];
	vendorsDist			= 'assets/dist/vendor/';

function copyVendors(){
	return src(vendorsSrc)
		.pipe(gulpCopy(vendorsDist, { prefix: 1 }));
}

function js(){
	return src(jsSrc + '*.js')
		.pipe(uglify())
		.pipe(rename({ extname: '.min.js' }))
		.pipe(dest(jsDist));
}

function css(){
	return src(scssSrc + '*.scss')
		.pipe(sass())
		.pipe(cssClean())
		.pipe(rename({ extname: '.min.css' }))
		.pipe(dest(cssDist));
}

function watchSass(){
	watch([scssSrc + '*.scss'], function(css){
		css();
	})
}

exports.deploy = series( copyVendors, js, css );
exports.watch = series( watchSass );
