<?php
/**
 * Twenty'em WordPress Framework.
 *
 * WARNING: This file is part of Twenty'em WordPress Framework.
 * DO NOT edit this file under any circumstances. Do all your modifications in the form of a child theme.
 *
 * @package			WordPress
 * @subpackage		Twenty'em
 * @author			RogerTM
 * @license			license.txt
 * @link			https://themingisprose.com/twenty-em
 * @since 			Twenty'em 1.0
 */

/**
 * The Header for our theme.
 *
 * Displays all of the <head> section and everything up till <div id="main">
 */
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?> class="no-js no-svg">
<head>
	<?php wp_head(); ?>
</head>

<body <?php body_class(); ?>>
	<?php t_em_action_top(); ?>
<div id="wrap" class="hfeed">
	<?php t_em_action_header_before(); ?>
	<header id="header">
		<div id="branding" role="banner" class="container">
			<?php t_em_action_header_inside_before() ?>
			<div class="branding-inner row">
				<div class="col-md-6">
					<?php t_em_action_header_inside_left(); ?>
				</div>
				<div class="col-md-6">
					<?php t_em_action_header_inside_right(); ?>
				</div>
			</div><!-- .branding-inner -->
			<?php t_em_action_header_inside_after(); ?>
		</div><!-- #branding .wrapper .container -->
	</header><!-- #header -->

	<?php t_em_action_header_after(); ?>

	<div id="main">
		<?php t_em_action_main_before(); ?>
		<div id="inner-main" class="container">

