<?php
/**
 * Twenty'em WordPress Framework.
 *
 * WARNING: This file is part of Twenty'em WordPress Framework.
 * DO NOT edit this file under any circumstances. Do all your modifications in the form of a child theme.
 *
 * @package			WordPress
 * @subpackage		Twenty'em
 * @author			RogerTM
 * @license			license.txt
 * @link			https://themingisprose.com/twenty-em
 * @since 			Twenty'em 1.0.1
 */

/**
 * If Maintenance Mode option is active in the admin panel, this file is loaded before any other
 * template file
 *
 * @link http://codex.wordpress.org/Template_Hierarchy
 */

get_header( 'maintenance-mode' ); ?>
			<section id="main-content" <?php t_em_breakpoint( 'one-column' ); ?>>
				<section id="content" role="main" <?php t_em_breakpoint( 'one-column' ); ?>>
				<?php do_action( 't_em_action_maintenance_mode_before' ); ?>
				<?php t_em_maintenance_mode_area(); ?>
				<?php do_action( 't_em_action_maintenance_mode_after' ); ?>
				</section><!-- #content -->
			</section><!-- #main-content -->
<?php get_footer( 'maintenance-mode' ); ?>
