<?php
/**
 * Twenty'em WordPress Framework.
 *
 * WARNING: This file is part of Twenty'em WordPress Framework.
 * DO NOT edit this file under any circumstances. Do all your modifications in the form of a child theme.
 *
 * @package			WordPress
 * @subpackage		Twenty'em
 * @author			RogerTM
 * @license			license.txt
 * @link			https://themingisprose.com/twenty-em
 * @since 			Twenty'em 1.0
 */

/**
 * Template for displaying search forms.
 */
?>
<form id="searchform" action="<?php echo home_url( '/' ); ?>" method="get">
	<div class="input-group">
		<label class="sr-only" for="s"><?php _e( 'Search in', 't_em' ); ?> <?php echo bloginfo( 'name' ); ?></label>
		<input type="text" class="form-control" name="s" id="s" value="<?php the_search_query(); ?>" placeholder="<?php _e( 'Search', 't_em' ) ?>" />
		<span class="input-group-btn">
			<button class="btn btn-secondary" type="submit" title="<?php _e( 'Search', 't_em' ) ?>">
				<span class="icomoon-search"></span>
				<span class="label-btn sr-only"><?php _e( 'Search', 't_em' ) ?></span>
			</button>
		</span>
	</div>
</form>
