<?php
/**
 * Twenty'em WordPress Framework.
 *
 * WARNING: This file is part of Twenty'em WordPress Framework.
 * DO NOT edit this file under any circumstances. Do all your modifications in the form of a child theme.
 *
 * @package			WordPress
 * @subpackage		Twenty'em
 * @author			RogerTM
 * @license			license.txt
 * @link			https://themingisprose.com/twenty-em
 * @since 			Twenty'em 1.3
 */

/**
 * Deprecated admin functions, vars, etc...
 */

/**
 * $t_em. Array. Contains all the options store in the data base.
 * See t_em_default_theme_options() in /engine/theme-options.php for a complete list of 'key' => 'value'
 * pairs
 *
 * $t_em is deprecated since Twenty'em 1.3
 * @deprecated 1.3
 */
$t_em = t_em();

/**
 * $t_em_theme_data. Array. Contains theme's information stored in style.css file.
 *
 * $t_em_theme_data is deprecated since Twenty'em 1.3
 * @deprecated 1.3
 */
$t_em_theme_data = array(
	'Name'			=> wp_get_theme()->display( 'Name' ),
	'ThemeURI'		=> esc_url( wp_get_theme()->display( 'ThemeURI' ) ),
	'Description'	=> wp_get_theme()->display( 'Description' ),
	'Author'		=> wp_get_theme()->display( 'Author' ),
	'AuthorURI'		=> esc_url( wp_get_theme()->display( 'AuthorURI' ) ),
	'Version'		=> wp_get_theme()->display( 'Version' ),
	'Template'		=> wp_get_theme()->display( 'Template' ),
	'Status'		=> wp_get_theme()->display( 'Status' ),
	'Tags'			=> wp_get_theme()->display( 'Tags' ),
	'TextDomain'	=> wp_get_theme()->display( 'TextDomain' ),
	'DomainPath'	=> wp_get_theme()->display( 'DomainPath' ),
);
?>
