<?php
/**
 * Twenty'em WordPress Framework.
 *
 * WARNING: This file is part of Twenty'em WordPress Framework.
 * DO NOT edit this file under any circumstances. Do all your modifications in the form of a child theme.
 *
 * @package			WordPress
 * @subpackage		Twenty'em
 * @author			RogerTM
 * @license			license.txt
 * @link			http://twenty-em.com/
 * @since 			Twenty'em 1.0
 */

/**
 * Twenty'em Layout theme options.
 */

/**
 * Return an array of Layout Options for Twenty'em admin panel.
 * This function manage how is displayed our theme layout. Possibles options are:
 * 0. Sidebar on right (two-column-content-left).
 * 1. Sidebar on left (two-column-content-right).
 * 2. One column, no sidebar (content).
 *
 * @return array
 *
 * @since Twenty'em 1.0
 */
function t_em_layout_options( $layout_options = '' ){
	$layout_options = array(
		'two-column-content-left' => array(
			'value' => 'two-column-content-left',
			'label' => __( 'Two columns. Content on left', 't_em' ),
			'thumbnail' => T_EM_ENGINE_DIR_IMG_URL . '/two-column-content-left.png',
		),
		'two-column-content-right' => array(
			'value' => 'two-column-content-right',
			'label' => __( 'Two columns. Content on right', 't_em' ),
			'thumbnail' => T_EM_ENGINE_DIR_IMG_URL . '/two-column-content-right.png',
		),
		'three-column-content-left' => array(
			'value' => 'three-column-content-left',
			'label' => __( 'Three columns. Content on left', 't_em' ),
			'thumbnail' => T_EM_ENGINE_DIR_IMG_URL . '/three-column-content-left.png',
		),
		'three-column-content-right' => array(
			'value' => 'three-column-content-right',
			'label' => __( 'Three columns. Content on right', 't_em' ),
			'thumbnail' => T_EM_ENGINE_DIR_IMG_URL . '/three-column-content-right.png',
		),
		'three-column-content-middle' => array(
			'value' => 'three-column-content-middle',
			'label' => __( 'Three columns. Content in the middle', 't_em' ),
			'thumbnail' => T_EM_ENGINE_DIR_IMG_URL . '/three-column-content-middle.png',
		),
		'one-column' => array(
			'value' => 'one-column',
			'label' => __( 'One column, no sidebar', 't_em' ),
			'thumbnail' => T_EM_ENGINE_DIR_IMG_URL . '/one-column.png',
		),
	);

	/**
	 * Filter the Layout Options Set
	 *
	 * @param array An array of new options in the Layout Options Set.
	 * 				Keyed by a string id. The ids point to arrays containing 'value', 'label', and 'thumbnail' keys.
	 * @since Twenty'em 1.0
	 */
	return apply_filters( 't_em_admin_filter_layout_options', $layout_options );
}

/**
 * Footer Widgets Options
 */
function t_em_footer_options( $footer_options = '' ){
	$footer_options = array(
		'four-footer-widget' => array(
			'value' => 'four-footer-widget',
			'label' => __( 'Four footer widget', 't_em' ),
			'thumbnail' => T_EM_ENGINE_DIR_IMG_URL . '/footer-widgets-four.png',
		),
		'three-footer-widget' => array(
			'value' => 'three-footer-widget',
			'label' => __( 'Three footer widget', 't_em' ),
			'thumbnail' => T_EM_ENGINE_DIR_IMG_URL . '/footer-widgets-three.png',
		),
		'two-footer-widget' => array(
			'value' => 'two-footer-widget',
			'label' => __( 'Two footer widget', 't_em' ),
			'thumbnail' => T_EM_ENGINE_DIR_IMG_URL . '/footer-widgets-two.png',
		),
		'one-footer-widget' => array(
			'value' => 'one-footer-widget',
			'label' => __( 'One footer widget', 't_em' ),
			'thumbnail' => T_EM_ENGINE_DIR_IMG_URL . '/footer-widgets-one.png',
		),
		'no-footer-widget' => array(
			'value' => 'no-footer-widget',
			'label' => __( 'No footer widgets', 't_em' ),
			'thumbnail' => T_EM_ENGINE_DIR_IMG_URL . '/footer-widgets-none.png',
		),
	);

	/**
	 * Filter the Footer Options Set
	 *
	 * @param array An array of new options in the Footer Options Set.
	 * 				Keyed by a string id. The ids point to arrays containing 'value', 'label', and 'thumbnail' keys.
	 * @since Twenty'em 1.0
	 */
	return apply_filters( 't_em_admin_filter_footer_options', $footer_options );
}

/**
 * Display a text box into Layout Options panel where you may enter your theme width.
 * Referenced via t_em_settings_field_layout_set().
 *
 * @return string HTML Text box form.
 *
 * @since Twenty'em 1.0
 */
function t_em_layout_width(){
	global $t_em;

	$layout_width = '';
	$layout_width .= '<div class="sub-extend option-group">';
	$layout_width .= 	'<header>'. __( 'Layout Width', 't_em' ) .'</header>';
	$layout_width .= 	'<div class="layout text-option layout-width">';
	$layout_width .= 		'<label>';
	$layout_width .= 		'<span>'. sprintf( __( 'Enter the value you wish to be your site width. Options: default: <code>%1$s</code>; max: <code>%2$s</code>; min: <code>%3$s</code>.', 't_em' ), T_EM_LAYOUT_WIDTH_DEFAULT_VALUE, T_EM_LAYOUT_WIDTH_MAX_VALUE, T_EM_LAYOUT_WIDTH_MIN_VALUE ) .'</span>';
	$layout_width .= 			'<input type="number" name="t_em_theme_options[layout_width]" value="'.$t_em['layout_width'].'" max="'. T_EM_LAYOUT_WIDTH_MAX_VALUE .'" min="'. T_EM_LAYOUT_WIDTH_MIN_VALUE .'" /><span class="unit">px</span>';
	$layout_width .= 		'</label>';
	$layout_width .= 	'</div>';
	$layout_width .= 	'<div class="layout text-option layout-width">';
	$layout_width .= 		'<label>';
	$checked_option = checked( $t_em['layout_fluid_width'], '1', false );
	$layout_width .= 			'<input type="checkbox" name="t_em_theme_options[layout_fluid_width]" value="1" '. $checked_option .' />';
	$layout_width .= 			__( 'Use full width container, spanning the entire width of your viewport.', 't_em' );
	$layout_width .= 		'</label>';
	$layout_width .= 	'</div>';
	$layout_width .= '</div>';

	echo $layout_width;
}
add_action( 't_em_admin_action_layout_options_after', 't_em_layout_width' );

/**
 * Render the Layout setting field in admin panel.
 * Referenced via t_em_register_setting_options_init(), add_settings_field() callback in
 * /engine/theme-options.php.
 *
 * @uses t_em_layout_width() Display a text box into Layout Options panel where you may enter
 * your theme width.
 *
 * @global $t_em.
 *
 * @since Twenty'em 1.0
 */
function t_em_settings_field_layout_set(){
	global $t_em;
?>
	<div id="layout-options">
		<?php do_action( 't_em_admin_action_layout_options_before' ); ?>
		<div class="sub-extend option-group">
			<header><?php _e( 'Main Layout Setting', 't_em' ); ?></header>
			<div class="image-radio-option-group">
<?php
			foreach ( t_em_layout_options() as $layout ) :
				$active_option = ( $t_em['layout_set'] == $layout['value'] ) ? 'radio-image radio-image-active' : 'radio-image';
?>
				<div class="layout image-radio-option theme-layout <?php echo $active_option ?>">
					<label class="description">
						<input class="input-image-radio-option" type="radio" name="t_em_theme_options[layout_set]" value="<?php echo esc_attr( $layout['value'] ) ?>" <?php checked( $t_em['layout_set'], $layout['value'] ); ?> />
						<span><img src="<?php echo esc_url( $layout['thumbnail'] ); ?>" alt="" /><p><?php echo $layout['label']; ?></p></span>
					</label>
				</div>
<?php
			endforeach;
?>
			</div>
		</div>

		<div class="sub-extend option-group">
			<header><?php _e( 'Footer Widgets Area Setting', 't_em' ); ?></header>
			<div class="image-radio-option-group">
<?php
			foreach ( t_em_footer_options() as $footer ) :
				$active_option = ( $t_em['footer_set'] == $footer['value'] ) ? 'radio-image radio-image-active' : 'radio-image';
?>
				<div class="footer image-radio-option theme-footer <?php echo $active_option ?>">
					<label class="description">
						<input class="input-image-radio-option" type="radio" name="t_em_theme_options[footer_set]" value="<?php echo esc_attr( $footer['value'] ) ?>" <?php checked( $t_em['footer_set'], $footer['value'] ); ?> />
						<span><img src="<?php echo esc_url( $footer['thumbnail'] ); ?>" alt="" /><p><?php echo $footer['label']; ?></p></span>
					</label>
				</div>
<?php
			endforeach;
?>
			</div>
		</div>
		<?php do_action( 't_em_admin_action_layout_options_after' ); ?>
	</div><!-- #layout-options -->
<?php
}
?>
