<?php
/**
 * Twenty'em WordPress Framework.
 *
 * WARNING: This file is part of Twenty'em WordPress Framework.
 * DO NOT edit this file under any circumstances. Do all your modifications in the form of a child theme.
 *
 * @package			WordPress
 * @subpackage		Twenty'em
 * @author			RogerTM
 * @license			license.txt
 * @link			https://themingisprose.com/twenty-em
 * @since 			Twenty'em 1.0
 */

/**
 * Twenty'em theme options.
 */

/**
 * Register the form setting for our t_em_theme_options array.
 * This function is attached to the admin_init() action hook.
 *
 * @uses register_setting() Register a setting and its sanitization callback.
 * @uses add_settings_section() This are groups of settings you see on Twenty'em settings pages with
 * a shared heading.
 * @uses add_settings_field() Register a settings field to a settings page and section.
 *
 * @link http://codex.wordpress.org/Settings_API
 *
 * @since Twenty'em 1.0
 */
function t_em_register_setting_options_init(){
	register_setting( 't_em_options', 't_em_theme_options', 't_em_theme_options_validate' );

	// Register our settings field group
	add_settings_section( 'twenty-em-section', '', '__return_false', 'twenty-em-options' );

	// Register our individual settings fields
	add_settings_field( 't_em_general_set',			__( 'General Options', 't_em' ),			't_em_settings_field_general_options_set',		'twenty-em-options',	'twenty-em-section' );
	add_settings_field( 't_em_header_set',			__( 'Header Options', 't_em' ),				't_em_settings_field_header_set',				'twenty-em-options',	'twenty-em-section' );
	add_settings_field( 't_em_front_page_set',		__( 'Front Page Options', 't_em' ),			't_em_settings_field_front_page_options_set',	'twenty-em-options',	'twenty-em-section' );
	add_settings_field( 't_em_archive_set',			__( 'Archive Options', 't_em' ),			't_em_settings_field_archive_set',				'twenty-em-options',	'twenty-em-section' );
	add_settings_field( 't_em_layout_set',			__( 'Layout Options', 't_em' ),				't_em_settings_field_layout_set',				'twenty-em-options',	'twenty-em-section' );
	add_settings_field( 't_em_social_set',			__( 'Social Network Options', 't_em' ),		't_em_settings_field_socialnetwork_set',		'twenty-em-options',	'twenty-em-section' );
	add_settings_field( 't_em_webmaster_tools_set', __( 'Webmaster Tools Options', 't_em' ),	't_em_settings_field_webmaster_tools_set', 		'twenty-em-options', 	'twenty-em-section' );
	add_settings_field( 't_em_maintenance_mode', 	__( 'Maintenance Mode Options', 't_em' ),	't_em_settings_field_maintenance_mode_set', 	'twenty-em-options', 	'twenty-em-section' );

	do_action( 't_em_admin_action_add_settings_field' );
}
add_action( 'admin_init', 't_em_register_setting_options_init' );

/**
 * Register Style Sheet and Javascript to beautify the admin option page.
 *
 * @since Twenty'em 1.0
 */
function t_em_admin_enqueue(){
	$screen = get_current_screen();
	if ( $screen->id == 'toplevel_page_twenty-em-options' ):
		// Check the theme version right from the style sheet
		wp_register_style( 'style-admin-t-em', T_EM_ENGINE_DIR_CSS_URL . '/theme-options.css', false, t_em_theme( 'Version' ), 'all' );
		wp_enqueue_style( 'style-admin-t-em' );
		wp_enqueue_script( 'jquery-ui-accordion' );
		wp_enqueue_script( 'jquery-ui-tabs' );
		wp_enqueue_script( 'jquery-ui-datepicker' );
		wp_register_script( 'script-admin-t-em', T_EM_ENGINE_DIR_JS_URL . '/theme-options.js', array( 'jquery', 'jquery-ui-accordion', 'jquery-ui-tabs', 'jquery-ui-datepicker' ), t_em_theme( 'Version' ), true );
		// L10n for theme-options.js
		$l10n = array(
			'upm_title'		=> __( 'Select Image', 't_em' ),
			'upm_button'	=> __( 'Use selected image', 't_em' ),
		);
		wp_localize_script( 'script-admin-t-em', 't_em_l10n_admin', $l10n );
		wp_enqueue_script( 'script-admin-t-em' );
		wp_enqueue_media();
		wp_enqueue_style( 'media' );
	endif;
}
add_action( 'admin_enqueue_scripts', 't_em_admin_enqueue' );

/**
 * Add our theme options page to the admin menu, including some help documentation.
 * This function is attached to the admin_menu() action hook.
 *
 * @since Twenty'em 1.0
 */
function t_em_theme_options_admin_page(){
	$svg = '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" style="fill:#82878c" viewBox="0 0 32 32"><title>twenty-em</title><path d="M29.7 23.6h-8.3l-6.4-11.1v-12.5h-12.7v12.6h12.5l6.5 11.2v8.2h8.4z"></path></svg>';
	$svg = 'data:image/svg+xml;base64,' . base64_encode( $svg );

	$theme_page 		= add_menu_page( T_EM_FRAMEWORK_NAME . ' ' . T_EM_FRAMEWORK_VERSION . ' ' . T_EM_FRAMEWORK_VERSION_STATUS, T_EM_FRAMEWORK_NAME, 'edit_theme_options', 'twenty-em-options', 't_em_theme_options_page', $svg, '2.25031992' );
	$theme_backup_page	= add_submenu_page( 'twenty-em-options', __( 'Backup', 't_em' ), __( 'Backup', 't_em' ), 'edit_theme_options', 'twenty-em-backup', 't_em_theme_backup' );

	// We call our help screens
	if ( ! $theme_page ) return;
	if ( ! $theme_backup_page ) return;

	add_action( "load-$theme_page", 't_em_theme_options_help' );
	add_action( "load-$theme_backup_page", 't_em_theme_backup_help' );
}
add_action( 'admin_menu', 't_em_theme_options_admin_page' );

/**
 * Add node to admin bar
 *
 * @since Twenty'em 1.3
 */
function t_em_add_node( $wp_admin_bar ){
	$svg = '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" style="fill:#82878c" viewBox="0 0 32 32"><title>twenty-em</title><path d="M29.7 23.6h-8.3l-6.4-11.1v-12.5h-12.7v12.6h12.5l6.5 11.2v8.2h8.4z"></path></svg>';
	$svg = 'data:image/svg+xml;base64,' . base64_encode( $svg );
	$style = array(
		'background-image: url('. $svg .');',
		'background-repeat: no-repeat;',
		'background-position: 0 6px;',
		'width: 20px;',
		'height: 30px;',
	);

	$args = array(
		'id'		=> 'twenty-em',
		'title'		=> '<div id="twenty-em-ab-icon" class="" style="'. implode( '', $style ) .'"><span class="screen-reader-text">'. T_EM_FRAMEWORK_NAME . ' ' . T_EM_FRAMEWORK_VERSION .'</span></div>',
		'href'		=> admin_url( 'admin.php?page=twenty-em-options' ),
	);
	$wp_admin_bar->add_node( $args );

	$args = array(
		'id'		=> 'twenty-em-options',
		'title'		=> T_EM_FRAMEWORK_NAME,
		'parent'	=> 'twenty-em',
		'href'		=> admin_url( 'admin.php?page=twenty-em-options' ),
	);
	$wp_admin_bar->add_node( $args );

	$args = array(
		'id'		=> 'twenty-em-backup',
		'title'		=> __( 'Backup', 't_em' ),
		'parent'	=> 'twenty-em',
		'href'		=> admin_url( 'admin.php?page=twenty-em-backup' ),
	);
	$wp_admin_bar->add_node( $args );
}
add_action( 'admin_bar_menu', 't_em_add_node', 100 );

/**
 * Finally a Options Page is displayed.
 * Referenced via t_em_theme_options_admin_page(), add_menu_page() callback
 *
 * @uses settings_fields() Output nonce, action, and option_page fields for a settings page.
 * @uses do_settings_sections() Prints out all settings sections added to /engine/theme-options.php.
 *
 * @link http://codex.wordpress.org/Settings_API
 * @link http://codex.wordpress.org/Administration_Menus
 *
 * @since Twenty'em 1.0
 */
function t_em_theme_options_page(){
?>
	<div class="wrap">
		<h2><?php echo T_EM_FRAMEWORK_NAME . ' ' . T_EM_FRAMEWORK_VERSION . ' ' . T_EM_FRAMEWORK_VERSION_STATUS ?></h2>
		<?php if ( t_em( 'maintenance_mode' ) ) : ?>
		<div class="updated" style="border-color:#00a0d2">
			<p><?php printf( __( 'You are using the <a href="%s"><strong>Maintenance Mode</strong></a>.', 't_em' ), wp_nonce_url( home_url( '/' ), 'maintenance_mode', 'maintenance-mode' ) ) ?></p>
		</div>
		<?php endif; ?>
		<?php if ( empty( t_em() ) ) : ?>
		<div class="error">
			<p><?php t_em_theme_explode(); ?></p>
		</div>
		<?php elseif ( t_em_db_version() < T_EM_DB_VERSION ) :
			// Check for updates!
			$options_diff = array_diff_key( t_em_default_theme_options(), t_em() );
			$options_update = array_merge( $options_diff, t_em() );
		?>
			<div class="updated">
		<?php 		if ( ! isset( $_GET['update-twenty-em'] ) ) : ?>
				<p><?php echo sprintf( __( 'Thank you for updating <strong>%1$s</strong>. Currently running <strong>Framework Version %2$s</strong> and <strong>Database Version %3$s</strong>. Before to continue, you need to update your database setting. For more security, please, <a href="%4$s">backup your setting</a>.', 't_em' ),
								T_EM_FRAMEWORK_NAME,
								T_EM_FRAMEWORK_VERSION,
								T_EM_DB_VERSION,
								admin_url( 'admin.php?page=twenty-em-backup' ) ); ?></p>
		<?php 		elseif ( isset( $_GET['update-twenty-em'] ) && $_GET['update-twenty-em'] == true ) : ?>
				<p><?php echo sprintf( __( 'Update completed. Back to <a href="%1$s">Theme Options</a> screen', 't_em' ), admin_url( 'admin.php?page=twenty-em-options' ) ) ?></p>
		<?php 		endif; ?>
			</div><!-- .updated -->

		<?php 		if ( ! isset( $_GET['update-twenty-em'] ) ) : ?>
			<a href="<?php echo admin_url( 'admin.php?page=twenty-em-options&amp;update-twenty-em=true' ) ?>" class="button button-hero button-primary">
				<?php printf( __( 'Update %s', 't_em' ), T_EM_FRAMEWORK_NAME ); ?>
			</a>
		<?php 		endif; ?>
		<?php 		if ( isset( $_GET['update-twenty-em'] ) && $_GET['update-twenty-em'] == true ) :
						update_option( 't_em_db_version', T_EM_DB_VERSION );
						update_option( 't_em_framework_version', T_EM_FRAMEWORK_VERSION );
						update_option( 't_em_theme_options', $options_update );
					endif;
		?>
		<?php else : ?>
			<?php settings_errors( 't-em-update' ); ?>
			<form id="t-em-setting" method="post" action="options.php">
				<?php
					settings_fields( 't_em_options' );
					do_settings_sections( 'twenty-em-options' );
					submit_button();
				?>
			</form>
		<?php endif; ?>
	</div><!-- .wrap -->
<?php
}

/**
 * Useful to generate an error code number when $input is totally null xD
 *
 * @return int Error code ID
 *
 * @since Twenty'em 1.0
 */
function t_em_rand_error_code(){
	echo sprintf( __( 'Oops! An error has occurred. Error ID: <strong>%1$s</strong>', 't_em' ), md5( rand() ) );
}

/**
 * Idem...
 */
function t_em_theme_explode(){
	echo sprintf( __( 'Oops! Your theme explode... Error ID: <strong>%1$s</strong>', 't_em' ), md5( rand() ) );
}

/**
 * And thank you all :)
 * This function is attached to the admin_footer_text Filter Hook
 *
 * @since Twenty'em 1.0
 */
function t_em_thank_you_all(){
	$text = sprintf( __( 'Thank you for creating with <a href="%s">WordPress</a> and <a href="%s">%s</a>.', 't_em' ),
						__( 'https://wordpress.org/' ),
						T_EM_SITE,
						T_EM_FRAMEWORK_NAME );
	return '<span id="footer-thankyou"><em>' . $text . '</em></span>';
}
add_filter( 'admin_footer_text', 't_em_thank_you_all' );
?>
