<?php
/**
 * Twenty'em WordPress Framework.
 *
 * WARNING: This file is part of Twenty'em WordPress Framework.
 * DO NOT edit this file under any circumstances. Do all your modifications in the form of a child theme.
 *
 * @package			WordPress
 * @subpackage		Twenty'em
 * @author			RogerTM
 * @license			license.txt
 * @link			https://themingisprose.com/twenty-em
 * @since 			Twenty'em 1.0
 */

/**
 * Silents is gold... But we call the others
 */

require_once( T_EM_THEME_DIR_INC_PATH . '/functions.php' );
require_once( T_EM_THEME_DIR_INC_PATH . '/enqueue.php' );
require_once( T_EM_THEME_DIR_INC_PATH . '/shortcodes.php' );
require_once( T_EM_THEME_DIR_INC_PATH . '/widgets.php' );
?>
