<?php
/**
 * Twenty'em Backup theme options.
 *
 * @file			theme-backup.php
 * @package			WordPress
 * @subpackage		Twenty'em
 * @author			RogerTM
 * @copyright		2012
 * @license			license.txt
 * @version			1.0
 * @filesource		wp-content/themes/twenty-em/inc/theme-backup.php
 * @link			N/A
 * @since			Twenty'em 1.0
 */
?>
<?php
/**
 * Generate a backup TXT file with all the theme options data.
 * Possible options are:
 * 0. Backup all settings. This contain all of the options listed below.
 * 1. Backup Theme options
 * 2. Backup Tools Box options
 * 3. Backup Webmaster Tools options
 *
 * @uses check_admin_referer() Tests either if the current request carries a valid nonce, or if the
 * current request was referred from an administration screen.
 *
 * @global $wpdb
 *
 * @link http://codex.wordpress.org/Function_Reference/check_admin_referer
 * @link http://codex.wordpress.org/Class_Reference/wpdb
 *
 * @since Twenty'em 1.0
 */
function t_em_backup_export(){
	global 	$wpdb, $file_header;

	// Check for security
	check_admin_referer( 't-em-backup-export' );

	$export_data = array ( 'all-setting', 'theme-options', 'toolsbox-options', 'webmastertools-options' );

	// Check for invalid exports
	if ( ! in_array( strip_tags( $_POST['export-data'] ), $export_data ) ) { return; }

	$export_type = esc_attr( strip_tags( $_POST['export-data'] ) );

	$export_option_prefix = array( 'Theme Options: ', 'Tools Box Options: ', 'Webmaster Tools Options: ' );

	$export_theme_options			= $export_option_prefix[0] .
									  $wpdb->get_var( $wpdb->prepare ("SELECT option_value
									  FROM $wpdb->options
									  WHERE option_name = %s",
									  't_em_theme_options' ) );

	$export_toolsbox_options		= $export_option_prefix[1] .
									  $wpdb->get_var( $wpdb->prepare ("SELECT option_value
									  FROM $wpdb->options
									  WHERE option_name = %s",
									  't_em_tools_box_options' ) );

	$export_webmastertools_options	= $export_option_prefix[2] .
									  $wpdb->get_var( $wpdb->prepare ("SELECT option_value
									  FROM $wpdb->options
									  WHERE option_name = %s",
									  't_em_webmaster_tools_options' ) );

									// We need to brake (\n) the string to explode it at importing time
	$export_all_setting				= $export_theme_options . "\n" .
									  $export_toolsbox_options . "\n" .
									  $export_webmastertools_options;

	switch ( $export_type ) :
		case 'all-setting':
			$exported_data = $export_all_setting;
			break;
		case 'theme-options':
			$exported_data = $export_theme_options;
			break;
		case 'toolsbox-options':
			$exported_data = $export_toolsbox_options;
			break;
		case 'webmastertools-options':
			$exported_data = $export_webmastertools_options;
			break;
		default:
			$exported_data = $export_all_setting;
			break;
	endswitch;

	if ( $exported_data == '' ) :
		wp_redirect( admin_url( 'admin.php?page=theme-backup&export-error=true' ) );
		exit;
	endif;

	/* Add our water mark. Only files with this water mark will be imported successfully.
	 * We encrypt this var in the output just to impress. :)
	 */
	$water_mark = 'twenty-em-backup-file';

	$output = md5( $water_mark ) . "\n";
	$output .= $export_type . "\n";
	$output .= $exported_data . "\n";
	$output .= __( 'WARNING: Do not edit this files. It contains your theme configuration settings', 't_em' ) . "\n";
	$output .= date( 'Y-m-d @ H:i:s' ) . "\n";

	// We create the export file
	header( 'Content-Description: File Transfer' );
	header( 'Content-Type: text/plain' );
	header( 'Content-Disposition: attachment; filename="t-em-backup-'. $export_type .'-'. date('Ymd-His') .'.txt"' );
	echo $output;
	exit();
} // t_em_backup_export()

/**
 * Upload file containing the backup settings
 * Possible options are:
 * 0. Import all settings. This contain all of the options listed below.
 * 1. Import Theme options
 * 2. Import Tools Box options
 * 3. Import Webmaster Tools options
 *
 * @uses check_admin_referer() Tests either if the current request carries a valid nonce, or if the
 * current request was referred from an administration screen.
 *
 * @global $wpdb
 *
 * @link http://codex.wordpress.org/Function_Reference/check_admin_referer
 * @link http://codex.wordpress.org/Class_Reference/wpdb
 *
 * @since Twenty'em 1.0
 */
function t_em_backup_import(){
	global $wpdb;

	// Check for security
	check_admin_referer( 't-em-backup-import' );

	$import_data = array ( 'all-setting', 'theme-options', 'toolsbox-options', 'webmastertools-options' );
	$import_option_prefix = array ( 'Theme Options: ', 'Tools Box Options: ', 'Webmaster Tools Options: ' );

	// If the import setting has not been sent, we do nothing
	if ( ! isset( $_FILES['import-theme-data'] ) ) { return; }

	// Check if the uploaded file is our file
	if ( is_uploaded_file( $_FILES['import-theme-data']['tmp_name'] ) ) :
		// Read the file and extract its content
		$upload_file = file_get_contents( $_FILES['import-theme-data']['tmp_name'] );

		// Stop! Who's coming?
		$whos_coming = explode( "\n", $upload_file );

		// Check for our water mark and so on...
		if ( $whos_coming[0] != md5( 'twenty-em-backup-file' ) || !in_array( $whos_coming[1], $import_data) ) :
			wp_redirect( admin_url( 'admin.php?page=theme-backup&error=true' ) );
			exit;
		endif;

		// Check for what we're gonna process
		if ( $whos_coming[1] == $import_data[0] ) :
			// All Settings
			// Searching needles in the stack of straw to clean the dunghill
			$dirty[0] = '/' . $whos_coming[0] . '/';
			$dirty[1] = '/' . $whos_coming[1] . '/'; // Setting Type
			$dirty[2] = '/' . $import_option_prefix[0] . '/'; // Theme Options
			$dirty[3] = '/' . $import_option_prefix[1] . '/'; // Tools Box Options
			$dirty[4] = '/' . $import_option_prefix[2] . '/'; // Webmaster Tools Options
			$dirty[5] = '/' . $whos_coming[5] . '/'; // WARNING
			$dirty[6] = '/' . $whos_coming[6] . '/'; // Date
			$clean[0] = '';
			$clean[1] = '';
			$clean[2] = '';
			$clean[3] = '';
			$clean[4] = '';
			$clean[5] = '';
			$clean[6] = '';
			$clean_export_string = preg_replace( $dirty, $clean, $upload_file );
			$split_export_string = explode( "\n", $clean_export_string );

			$wpdb->update(
					$wpdb->options,
					array( 'option_value' => $split_export_string[2] ),
					array( 'option_name' => 't_em_theme_options' )
				);
			$wpdb->update(
					$wpdb->options,
					array( 'option_value' => $split_export_string[3] ),
					array( 'option_name' => 't_em_tools_box_options' )
				);
			$wpdb->update(
					$wpdb->options,
					array( 'option_value' => $split_export_string[4] ),
					array( 'option_name' => 't_em_webmaster_tools_options' )
				);
		elseif ( $whos_coming[1] == $import_data[1] ) :
			// Theme Options
			// We do that about the dunghill
			$dirty[0] = '/' . $whos_coming[0] . '/';
			$dirty[1] = '/' . $whos_coming[1] . '/'; // Setting Type
			$dirty[2] = '/' . $import_option_prefix[0] . '/'; // Theme Options
			$dirty[3] = '/' . $whos_coming[3] . '/'; // WARNING
			$dirty[4] = '/' . $whos_coming[4] . '/'; // Date
			$clean[0] = '';
			$clean[1] = '';
			$clean[2] = '';
			$clean[3] = '';
			$clean[4] = '';
			$clean_export_string = preg_replace( $dirty, $clean, $upload_file );
			$split_export_string = explode( "\n", $clean_export_string );

			$wpdb->update(
					$wpdb->options,
					array( 'option_value' => $split_export_string[2] ),
					array( 'option_name' => 't_em_theme_options' )
				);
		elseif ( $whos_coming[1] == $import_data[2] ) :
			// Tools Box Options
			// Dunghill again
			$dirty[0] = '/' . $whos_coming[0] . '/';
			$dirty[1] = '/' . $whos_coming[1] . '/'; // Setting Type
			$dirty[2] = '/' . $import_option_prefix[1] . '/'; // Tools Box Options
			$dirty[3] = '/' . $whos_coming[3] . '/'; // WARNING
			$dirty[4] = '/' . $whos_coming[4] . '/'; // Date
			$clean[0] = '';
			$clean[1] = '';
			$clean[2] = '';
			$clean[3] = '';
			$clean[4] = '';
			$clean_export_string = preg_replace( $dirty, $clean, $upload_file );
			$split_export_string = explode( "\n", $clean_export_string );

			$wpdb->update(
					$wpdb->options,
					array( 'option_value' => $split_export_string[2] ),
					array( 'option_name' => 't_em_tools_box_options' )
				);
		elseif ( $whos_coming[1] == $import_data[3] ) :
			// Tools Box Options
			// Dunghill again and over again...
			$dirty[0] = '/' . $whos_coming[0] . '/';
			$dirty[1] = '/' . $whos_coming[1] . '/'; // Setting Type
			$dirty[2] = '/' . $import_option_prefix[2] . '/'; // Tools Box Options
			$dirty[3] = '/' . $whos_coming[3] . '/'; // WARNING
			$dirty[4] = '/' . $whos_coming[4] . '/'; // Date
			$clean[0] = '';
			$clean[1] = '';
			$clean[2] = '';
			$clean[3] = '';
			$clean[4] = '';
			$clean_export_string = preg_replace( $dirty, $clean, $upload_file );
			$split_export_string = explode( "\n", $clean_export_string );

			$wpdb->update(
					$wpdb->options,
					array( 'option_value' => $split_export_string[2] ),
					array( 'option_name' => 't_em_webmaster_tools_options' )
				);
		endif;

	$wpdb->flush();

	endif;
} // t_em_backup_import()

/**
 * Prints notices massages on the screen, after export or import are performed
 */
function t_em_backup_notice(){
	if ( isset( $_GET['error'] ) && $_GET['error'] == true ) :
		echo '<div id="error-massage" class="error"><p>'. __( 'There was an error importing your data. Please try again', 't_em' ) .'</p></div>';
	elseif ( isset( $_GET['export-error'] ) && $_GET['export-error'] == true ) :
		echo '<div id="error-massage" class="error"><p>'. __( 'There was an error exporting your data. Please try again', 't_em' ) .'</p></div>';
	endif;
}

if ( ! isset( $_POST['t-em-backup-import'] ) && isset( $_POST['t-em-backup-export'] ) && $_POST['t-em-backup-export'] == true ) :
	t_em_backup_export();
endif;
if ( ! isset( $_POST['t-em-backup-export'] ) && isset( $_POST['t-em-backup-import'] ) && $_POST['t-em-backup-import'] == true ) :
	t_em_backup_import();
endif;

function t_em_theme_backup(){
?>
	<div class="wrap">
		<?php screen_icon(); ?>
		<h2><?php echo wp_get_theme() . ' ' . __( 'Backup', 't_em' ); ?></h2>
		<section id="export-settings">
			<h3><?php _e( 'Export Settings', 't_em' ); ?></h3>
			<?php t_em_backup_notice(); ?>
			<p><?php _e( 'When you click in the button below <strong>Twenty&#8217;em Framework</strong> will create an TXT file for you to save in your computer.', 't_em' ); ?></p>
			<p><?php _e( 'This file contain all your theme configuration. You can use it to restore your setting in this site or to easily setup another site based on <strong>Twenty&#8217;em Framework</strong>.', 't_em' ); ?></p>
			<form action="<?php echo admin_url( 'admin.php?page=theme-backup' ); ?>" method="post">
				<?php wp_nonce_field( 't-em-backup-export' ); ?>
				<p><label>
					<input type="radio" name="export-data" value="all-setting" checked="checked" />
					<?php _e( 'All Settings', 't_em' ); ?>
					<?php _e( '<span class="description">This option contain all the options listed below.</span>', 't_em' ); ?>
				</label></p>
				<p><label>
					<input type="radio" name="export-data" value="theme-options" />
					<?php _e( 'Theme Options', 't_em' ); ?>
				</label></p>
				<p><label>
					<input type="radio" name="export-data" value="toolsbox-options" />
					<?php _e( 'Tools Box Options', 't_em' ); ?>
				</label></p>
				<p><label>
					<input type="radio" name="export-data" value="webmastertools-options" />
					<?php _e( 'Webmaster Tools Options', 't_em' ); ?>
				</label></p>
				<?php submit_button( __( 'Download export file', 't_em' ) ); ?>
				<input type="hidden" name="t-em-backup-export" value="true" />
			</form>
		</section><!-- #export-settings -->

		<section id="import-settings">
			<h3><?php _e( 'Import Settings', 't_em' ); ?></h3>
			<p><?php _e( 'If you have your settings in a backup file in your computer, <strong>Twenty&#8217;em Framework</strong> can import those settings into this site', 't_em' ); ?></p>
			<form enctype="multipart/form-data" action="<?php echo admin_url( 'admin.php?page=theme-backup' ); ?>" method="post" id="import-theme-data">
				<?php wp_nonce_field( 't-em-backup-import' ); ?>
				<label>
					<?php printf( __( 'Upload File: (Maximum Size: %s)', 't_em' ), ini_get( 'post_max_size' ) ); ?><br />
					<input type="file" name="import-theme-data" id="import-theme-data" />
				</label>
				<?php submit_button( __( 'Upload file and import', 't_em' ) ); ?>
				<input type="hidden" name="t-em-backup-import" value="true" />
			</form>
		</section><!-- #import-settings -->
	</div>
<?php
}
?>
