<?php
/**
 * Twenty'em WordPress Framework.
 *
 * WARNING: This file is part of Twenty'em WordPress Framework.
 * DO NOT edit this file under any circumstances. Do all your modifications in the form of a child theme.
 *
 * @package			WordPress
 * @subpackage		Twenty'em
 * @author			RogerTM
 * @license			license.txt
 * @link			https://themingisprose.com/twenty-em
 * @since 			Twenty'em 1.2
 */

if ( ! function_exists( 't_em_comment' ) ) :
/**
 * Pluggable Function: Template for comments.
 *
 * To override this walker in a child theme without modifying the comments template
 * simply create your own t_em_comment(), and that function will be used instead.
 *
 * Used as a callback by wp_list_comments() for displaying the comments.
 *
 * @since Twenty'em 1.0
 */
function t_em_comment( $comment, $args, $depth ) {
	$GLOBALS['comment'] = $comment;
	switch ( $comment->comment_type ) :
		case '' :
	?>
	<li id="li-comment-<?php comment_ID(); ?>" <?php comment_class( 'mb-3' ); ?>>
		<article id="comment-<?php comment_ID(); ?>" class="comment-wrap media d-flex my-1">
			<div class="d-flex mr-3"><?php echo get_avatar( $comment, '', '', get_comment_author() ); ?></div>
			<div class="media-body">
				<footer class="comment-author vcard mt-0 mb-1">
					<?php printf( __( '<b class="fn">%1$s</b><span class="says sr-only">says:</span>', 't_em' ), get_comment_author_link() ); ?>
					<?php if ( $comment->comment_approved == '0' ) : ?>
						<em><?php _e( 'Your comment is awaiting moderation.', 't_em' ); ?></em>
						<br />
					<?php endif; ?>

					<div class="comment-meta commentmetadata"><a href="<?php echo esc_url( get_comment_link( $comment->comment_ID ) ); ?>">
					<?php /* translators: 1: date, 2: time */
						printf( __( '%1$s at %2$s', 't_em' ), get_comment_date(),  get_comment_time() ); ?>
						<small><?php edit_comment_link( __('Edit', 't_em'), '<span class="icomoon-edit"></span>' ); ?></small></a>
					</div><!-- .comment-meta .commentmetadata -->
				</footer><!-- comment-heading -->
				<div class="comment-body"><?php comment_text(); ?></div>

				<div class="reply">
					<?php comment_reply_link( array_merge( $args, array( 'depth' => $depth, 'max_depth' => $args['max_depth'] ) ) ); ?>
				</div><!-- .reply -->
			</div><!-- .media-body -->
		</article><!-- #comment-## .comment-wrap -->
	<?php
			break;
	endswitch;
}
endif; // function t_em_comment()

if ( ! function_exists( 't_em_comment_pingback_trackback' ) ) :
/**
 * Pluggable Function: Template for pingbacks and trackbacks.
 *
 * To override this walker in a child theme without modifying the comments template
 * simply create your own t_em_comment_pingback_trackback(), and that function will be used instead.
 *
 * Used as a callback by wp_list_comments() for displaying the comments.
 *
 * @since Twenty'em 1.0
 */
function t_em_comment_pingback_trackback( $comment, $args, $depth ) {
	$GLOBALS['comment'] = $comment;
	if ( ! comment )
		return;

	switch ( $comment->comment_type ) :
		case 'pingback' :
	?>
	<li id="comment-<?php comment_ID(); ?>" <?php comment_class(); ?>>
		<?php _e( 'Pingback:', 't_em' ); ?> <?php comment_author_link(); ?> <small><?php edit_comment_link( __('Edit', 't_em'), '<span class="icomoon-edit"></span>' ); ?></small>
		<div class="comment-body"><?php comment_text(); ?></div>
	<?php
			break;
		case 'trackback' :
	?>
	<li id="comment-<?php comment_ID(); ?>" <?php comment_class(); ?>>
		<?php _e( 'Trackback:', 't_em' ); ?> <?php comment_author_link(); ?> <small><?php edit_comment_link( __('Edit', 't_em'), '<span class="icomoon-edit"></span>' ); ?></small>
		<div class="comment-body"><?php comment_text(); ?></div>
	<?php
		break;
	endswitch;
}
endif; // function t_em_comment_pingback_trackback()

if ( ! function_exists( 't_em_comment_all' ) ) :
/**
 * Pluggable Function: Template for comments, pingbacks and trackbacks
 *
 * To override this walker in a child theme without modifying the comments template
 * simply create your own t_em_comment_pingback_trackback(), and that function will be used instead.
 *
 * Used as a callback by wp_list_comments() for displaying the comments.
 *
 * @since Twenty'em 1.0
 */
function t_em_comment_all( $comment, $args, $depth ){
	$GLOBALS['comment'] = $comment;
	switch ( $comment->comment_type ) :
		case 'pingback' :
	?>
	<li id="comment-<?php comment_ID(); ?>" <?php comment_class(); ?>>
		<?php _e( 'Pingback:', 't_em' ); ?> <?php comment_author_link(); ?> <small><?php edit_comment_link( __('Edit', 't_em'), '<span class="icomoon-edit"></span>' ); ?></small>
		<div class="comment-body"><?php comment_text(); ?></div>
	<?php
			break;
		case 'trackback' :
	?>
	<li id="comment-<?php comment_ID(); ?>" <?php comment_class(); ?>>
		<?php _e( 'Trackback:', 't_em' ); ?> <?php comment_author_link(); ?> <small><?php edit_comment_link( __('Edit', 't_em'), '<span class="icomoon-edit"></span>' ); ?></small>
		<div class="comment-body"><?php comment_text(); ?></div>
	<?php
			break;
		default :
		t_em_comment( $comment, $args, $depth );
		break;
	endswitch;
}
endif; // function t_em_comment_all()

if ( ! function_exists( 't_em_comments_template' ) ) :
/**
 * Pluggable Function: Display comments template
 *
 * @since Twenty'em 1.0
 */
function t_em_comments_template(){
	global $t_em;
	if ( comments_open() || get_comments_number() ) :
		if ( ( is_single() )
			|| ( is_page() && $t_em['single_page_comments'] ) ) :
			return comments_template( '', true );
		endif;
	endif;
}
endif; // function t_em_comments_template()
?>
