<?php
/**
 * Twenty'em WordPress Framework.
 *
 * WARNING: This file is part of Twenty'em WordPress Framework.
 * DO NOT edit this file under any circumstances. Do all your modifications in the form of a child theme.
 *
 * @package			WordPress
 * @subpackage		Twenty'em
 * @author			RogerTM
 * @license			license.txt
 * @link			https://themingisprose.com/twenty-em
 * @since 			Twenty'em 1.2
 */

/**
 * Silents is gold... But we call the others
 */

require_once( T_EM_THEME_DIR_TEMPLATES_PATH . '/init.php' );
require_once( T_EM_THEME_DIR_TEMPLATES_PATH . '/header.php' );
require_once( T_EM_THEME_DIR_TEMPLATES_PATH . '/head.php' );
require_once( T_EM_THEME_DIR_TEMPLATES_PATH . '/navigation.php' );
require_once( T_EM_THEME_DIR_TEMPLATES_PATH . '/front.php' );
require_once( T_EM_THEME_DIR_TEMPLATES_PATH . '/content.php' );
require_once( T_EM_THEME_DIR_TEMPLATES_PATH . '/comments.php' );
require_once( T_EM_THEME_DIR_TEMPLATES_PATH . '/meta.php' );
require_once( T_EM_THEME_DIR_TEMPLATES_PATH . '/footer.php' );
require_once( T_EM_THEME_DIR_TEMPLATES_PATH . '/forms.php' );
require_once( T_EM_THEME_DIR_TEMPLATES_PATH . '/call-actions.php' );
require_once( T_EM_THEME_DIR_TEMPLATES_PATH . '/maintenance-mode.php' );
?>
