<?php
/**
 * Twenty'em WordPress Framework.
 *
 * WARNING: This file is part of Twenty'em WordPress Framework.
 * DO NOT edit this file under any circumstances. Do all your modifications in the form of a child theme.
 *
 * @package			WordPress
 * @subpackage		Twenty'em
 * @author			RogerTM
 * @license			license.txt
 * @link			https://themingisprose.com/twenty-em
 * @since 			Twenty'em 1.2
 */

/**
 * Sets up theme defaults and registers the various WordPress features that Twenty'em supports.
 *
 * @uses add_theme_support() To add support for thumbnails, automatic feed links, post formats,
 * custom background, custom header.
 * All this functions are treat as pluggable, so they can be override in Child Themes.
 *
 * @link http://codex.wordpress.org/Theme_Features Visit for full documentation about Theme Features
 *
 * @return void
 *
 * @since Twenty'em 1.0
 */
function t_em_setup(){

	// Adds support featured image.
	add_theme_support( 'post-thumbnails' );

	// Adds RSS feed links to <head> for posts and comments.
	add_theme_support( 'automatic-feed-links' );

	// Adds support for variety of post formats.
	add_theme_support( 'post-formats', array( 'aside', 'link', 'gallery', 'status', 'quote', 'image', 'video', 'audio' ) );

	// Adds support for custom background
	add_theme_support( 'custom-background', array( 'default-color' => 'fff' ) );

	// This theme styles the visual editor with editor-style.css to match the theme style
	add_editor_style( 'css/editor-style.css' );

	// Adds support for custom header.
	$custom_header_support = array(
		/**
		 * Filter header image Width and Height
		 *
		 * @param int Width and Height values
		 * @since Twenty'em 1.0
		 */
		'width'						=> apply_filters( 't_em_filter_header_image_width', T_EM_HEADER_IMAGE_WIDTH ),
		'height'					=> apply_filters( 't_em_filter_header_image_height', T_EM_HEADER_IMAGE_HEIGHT ),
		'flex-width'				=> true,
		'flex-height'				=> true,
		'random-default'			=> true,
		'uploads'					=> true,
	);
	add_theme_support( 'custom-header', $custom_header_support );

	/*
	 * Let WordPress manage the document title.
	 * By adding theme support, we declare that this theme does not use a
	 * hard-coded <title> tag in the document head, and expect WordPress to
	 * provide it for us.
	 */
	add_theme_support( 'title-tag' );

	/*
	 * Switch default core markup for search form, comment form, and comments
	 * to output valid HTML5.
	 */
	add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption' ) );

	// Add theme support for Custom Logo.
	$custom_logo = array(
		'flex-width'	=> true,
		'flex-height'	=> true,
	);
	/**
	 * Filters Twenty'em array for custom logo
	 * @param array $custom_logo Array of custom logo
	 *
	 * @since Twenty'em 1.1.1
	 */
	add_theme_support( 'custom-logo', apply_filters( 't_em_filter_custom_logo', $custom_logo ) );

	// Add theme support for selective refresh for widgets.
	add_theme_support( 'customize-selective-refresh-widgets' );

	// Define and register starter content to showcase the theme on new sites.
	$starter_content = array(
		'widgets'	=> array(
			'sidebar'	=> array(
				'search'	=> array(
					'title'	=> '',
				),
				'recent-posts',
				'recent-comments',
				'categories',
				'archives',
			),
			'first-footer-widget-area'	=> array(
				'text_about'	=> array(
					'title'	=> sprintf( __( 'Welcome to %s', 't_em' ), T_EM_FRAMEWORK_NAME ),
					'text'	=> join( '', array(
						sprintf( __( '<p><strong>%s</strong> is a Theme/Framework for WordPress specially designed to create Child Themes</p>', 't_em' ), T_EM_FRAMEWORK_NAME ),
						sprintf( __( '<p><strong>%s</strong> offers you an ample number of options which allow you to perform your site easily</p>', 't_em' ), T_EM_FRAMEWORK_NAME ),
					) )
				),
			),
			'second-footer-widget-area'	=> array(
				'text_about'
			),
			'third-footer-widget-area'	=> array(
				'text_business_info',
			),
			'fourth-footer-widget-area'	=> array(
				'meta',
			),
		),
		'posts' => array(
			'home',
			'about',
			'contact',
			'blog'	=> array(
				'template'	=> 'page-templates/template-blog-excerpt.php',
			),
		),
		'nav_menus'	=> array(
			'top-menu'	=> array(
				'name'	=> __( 'Top Menu', 't_em' ),
				'items' => array(
					'link_home',
					'page_about',
					'page_blog',
					'page_contact',
				),
			),
			'navigation-menu'	=> array(
				'name'	=> __( 'Navigation Menu', 't_em' ),
				'items' => array(
					'link_home',
					'page_about',
					'page_blog',
					'page_contact',
				),
			),
			'footer-menu'	=> array(
				'name'	=> __( 'Footer Menu', 't_em' ),
				'items' => array(
					'link_home',
					'page_about',
					'page_blog',
					'page_contact',
				),
			),
		),
	);

	/**
	 * Filters Twenty'em array of starter content.
	 * @param array $starter_content Array of starter content.
	 *
	 * @since Twenty'em 1.1.1
	 */
	$starter_content = apply_filters( 't_em_filter_starter_content', $starter_content );

	add_theme_support( 'starter-content', $starter_content );

	// Default custom headers packaged with the theme.
	register_default_headers( array(
		'aqua'	=> array(
				'url'			=> T_EM_THEME_DIR_IMG_URL . '/headers/aqua.png',
				'thumbnail_url'	=> T_EM_THEME_DIR_IMG_URL . '/headers/aqua-thumbnail.png',
				'description'	=> _x( 'Aqua', 'header image description', 't_em' ),
			),
		'fire'	=> array(
				'url'			=> T_EM_THEME_DIR_IMG_URL . '/headers/fire.png',
				'thumbnail_url'	=> T_EM_THEME_DIR_IMG_URL . '/headers/fire-thumbnail.png',
				'description'	=> _x( 'Fire', 'header image description', 't_em' ),
			),
		'lime'	=> array(
				'url'			=> T_EM_THEME_DIR_IMG_URL . '/headers/lime.png',
				'thumbnail_url'	=> T_EM_THEME_DIR_IMG_URL . '/headers/lime-thumbnail.png',
				'description'	=> _x( 'Lime', 'header image description', 't_em' ),
			),
		'purple'	=> array(
				'url'			=> T_EM_THEME_DIR_IMG_URL . '/headers/purple.png',
				'thumbnail_url'	=> T_EM_THEME_DIR_IMG_URL . '/headers/purple-thumbnail.png',
				'description'	=> _x( 'Purple', 'header image description', 't_em' ),
			),
		)
	);

	// This theme uses navigation menus in three locations. Woew!
	register_nav_menus ( array(
		'top-menu'			=> __('Top Menu', 't_em'),
		'navigation-menu'	=> __('Navigation Menu', 't_em'),
		'footer-menu'		=> __('Footer Menu', 't_em'),
		)
	);

	/* Make Twenty'em available for translation.
	 * Translations can be added to the language/ directory.
	 * If you're building a theme based on Twenty'em, use a find and replace to change 't_em'
	 * to the name of your theme in all the template files.
	 */
	load_theme_textdomain( 't_em', T_EM_THEME_DIR_LANG_PATH );

}
add_action( 'after_setup_theme', 't_em_setup' );

/**
 * Add Twenty'em layout classes to the array of body classes.
 * This function is attached to the 'body_class' filter hook.
 *
 * @since Twenty'em 1.0
 */
function t_em_layout_classes( $existing_classes ){
	global $t_em;
	$layout_set = $t_em['layout_set'];

	// In front page and 'front-page-set => widgets-front-page' one column is enough
	if ( $t_em['front_page_set'] == 'widgets-front-page' && is_front_page() ) :
		$classes = array( 'one-column widgets-front-page' );
	elseif ( in_array( $layout_set, array( 'two-columns-content-left', 'two-columns-content-right' ) ) ) :
		$classes = array( 'two-columns' );
	elseif ( in_array( $layout_set, array( 'three-columns-content-left', 'three-columns-content-right', 'three-columns-content-middle' ) ) ) :
		$classes = array( 'three-columns' );
	else :
		$classes = array( 'one-column' );
	endif;

	if ( in_array( $layout_set, array( 'two-columns-content-left', 'three-columns-content-left' ) ) ) :
		$classes = array( 'content-left' );
	elseif ( in_array( $layout_set, array( 'two-columns-content-right', 'three-columns-content-right' ) ) ) :
		$classes = array( 'content-right' );
	elseif ( in_array( $layout_set, array( 'three-columns-content-middle' ) ) ) :
		$classes = array( 'content-middle' );
	endif;

	$classes[] = $layout_set;

	/**
	 * Add maintenance-mode and maintenance-mode-is-admin class if Maintenance Mode is active
	 *
	 * @since Twenty'em 1.0.1
	 */
	if ( $t_em['maintenance_mode'] ) :
		$classes[] = 'maintenance-mode';
		if ( is_user_logged_in() && current_user_can( 'manage_options' ) ) :
			$classes[] = 'maintenance-mode-is-admin';
		endif;
	endif;

	/**
	 * Add is-container-fluid class if full width is active
	 *
	 * @since Twenty'em 1.0.1
	 */
	if ( $t_em['layout_fluid_width'] ) :
		$classes[] = 'is-container-fluid';
	endif;

	return array_merge( $existing_classes, $classes );
}
add_filter( 'body_class', 't_em_layout_classes' );

/**
 * Add Twenty'em archive classes to the array of posts classes.
 * This function is attached to the 'post_class' filter hook.
 *
 * @since Twenty'em 1.0
 */
function t_em_archive_classes( $existing_classes ){
	global $t_em;
	$archive_set = $t_em['archive_set'];
	$excerpt_set = $t_em['excerpt_set'];

	if ( 'the-excerpt' == $archive_set && ! is_singular() ) :
		if ( 'thumbnail-left' == $excerpt_set ) :
			$classes[] = 'thumbnail-left';
		elseif ( 'thumbnail-right' == $excerpt_set ) :
			$classes[] = 'thumbnail-right';
		else :
			$classes[] = 'thumbnail-center';
		endif;
		$classes[] = 'excerpt-post';
	else :
		$classes[] = 'full-post';
	endif;

	return array_merge( $existing_classes, $classes );
}
add_filter( 'post_class', 't_em_archive_classes' );

/**
 * Custom Logo class
 * This function is attached to the 'get_custom_logo' filter hook.
 *
 * @since Twenty'em 1.1.1
 * @since Twenty'em 1.2 	Display site name
 */
function t_em_custom_logo_class( $html ){
	$logo_id = get_theme_mod( 'custom_logo' );
	$logo_src = wp_get_attachment_url( $logo_id );
	$heading_tag = ( is_home() || is_front_page() ) ? 'h1' : 'span';
	$html = '<a href="'. esc_url( home_url( '/' ) ) .'" class="custom-logo-link navbar-brand">
				<img class="custom-logo" src="'. $logo_src .'"/>
				<'. $heading_tag .' id="site-title">'. get_bloginfo( 'name' ) .'</'. $heading_tag .'>
			</a>';
	return $html;
}
add_filter( 'get_custom_logo', 't_em_custom_logo_class' );

/**
 * Set the post excerpt length depending of the $t_em['excerpt_length'] value.
 * You don't need to override this value in a Child Theme, just because you can set this value from
 * the Twenty'em Framework interface.
 *
 * @since Twenty'em 1.0
 */
function t_em_excerpt_length( $length ){
	global $t_em;
	return $t_em['excerpt_length'];
}
add_filter( 'excerpt_length', 't_em_excerpt_length' );

/**
 * Sets up the content width value based on the theme's design and stylesheet.
 */
if ( ! isset( $content_width ) ) :
	$content_width = 1200;
endif;

/**
 * Twenty'em shows a home link in wp_page_menu(), wp_nav_menu() fallback.
 *
 * @since Twenty'em 1.0
 */
function t_em_page_menu_args( $args ) {
	$args['show_home'] = true;
	return $args;
}
add_filter( 'wp_page_menu_args', 't_em_page_menu_args' );

/**
 * Register widgetized areas, including two sidebars and four widget-ready columns in the footer.
 * This function is attached to the widgets_init hook.
 * Note: Sidebars are enables just if they are needed
 *
 * @uses register_sidebar()
 *
 * @since Twenty'em 1.0
 */
function t_em_widgets_init() {
	global $t_em;

	// Sidebars Widgets Area
	if ( 'one-column' != $t_em['layout_set'] ) :
		// Area 0, located at the top of the sidebar.
		register_sidebar( array(
			'name' => __( 'Main Sidebar Widget Area', 't_em' ),
			'id' => 'sidebar',
			'description' => __( 'Add widgets here to appear in your main sidebar', 't_em' ),
			'before_widget' => '<aside id="%1$s" class="widget-container %2$s">',
			'after_widget' => '</aside>',
			'before_title' => '<h3 class="widget-title">',
			'after_title' => '</h3>',
		) );
	endif;

	if ( in_array( $t_em['layout_set'],
			array('three-columns-content-left', 'three-columns-content-right', 'three-columns-content-middle' )
		) ) :
		// Area 1, located at the top of the sidebar.
		register_sidebar( array(
			'name' => __( 'Alternative Sidebar Widget Area', 't_em' ),
			'id' => 'sidebar-alt',
			'description' => __( 'Add widgets here to appear in your alternative sidebar', 't_em' ),
			'before_widget' => '<aside id="%1$s" class="widget-container %2$s">',
			'after_widget' => '</aside>',
			'before_title' => '<h3 class="widget-title">',
			'after_title' => '</h3>',
		) );
	endif;

	// Footer Widgets Area
	if ( $t_em['footer_set'] != 'no-footer-widget' ) :
			// Area 2, located in the footer. Empty by default.
			register_sidebar( array(
				'name' => __( 'First Footer Widget Area', 't_em' ),
				'id' => 'first-footer-widget-area',
				'description' => __( 'Add widgets here to appear in your footer sidebar', 't_em' ),
				'before_widget' => '<div id="%1$s" class="widget-container %2$s">',
				'after_widget' => '</div>',
				'before_title' => '<h3 class="widget-title">',
				'after_title' => '</h3>',
			) );

		if ( in_array( $t_em['footer_set'],
				array( 'two-footer-widget', 'three-footer-widget', 'four-footer-widget' )
			) ) :
			// Area 3, located in the footer. Empty by default.
			register_sidebar( array(
				'name' => __( 'Second Footer Widget Area', 't_em' ),
				'id' => 'second-footer-widget-area',
				'description' => __( 'Add widgets here to appear in your footer sidebar', 't_em' ),
				'before_widget' => '<div id="%1$s" class="widget-container %2$s">',
				'after_widget' => '</div>',
				'before_title' => '<h3 class="widget-title">',
				'after_title' => '</h3>',
			) );
		endif;

		if ( in_array( $t_em['footer_set'],
				array( 'three-footer-widget', 'four-footer-widget' )
			) ) :
			// Area 4, located in the footer. Empty by default.
			register_sidebar( array(
				'name' => __( 'Third Footer Widget Area', 't_em' ),
				'id' => 'third-footer-widget-area',
				'description' => __( 'Add widgets here to appear in your footer sidebar', 't_em' ),
				'before_widget' => '<div id="%1$s" class="widget-container %2$s">',
				'after_widget' => '</div>',
				'before_title' => '<h3 class="widget-title">',
				'after_title' => '</h3>',
			) );
		endif;

		if ( in_array( $t_em['footer_set'],
				array( 'four-footer-widget' )
			) ) :
			// Area 5, located in the footer. Empty by default.
			register_sidebar( array(
				'name' => __( 'Fourth Footer Widget Area', 't_em' ),
				'id' => 'fourth-footer-widget-area',
				'description' => __( 'Add widgets here to appear in your footer sidebar', 't_em' ),
				'before_widget' => '<div id="%1$s" class="widget-container %2$s">',
				'after_widget' => '</div>',
				'before_title' => '<h3 class="widget-title">',
				'after_title' => '</h3>',
			) );
		endif;
	endif;
}
add_action( 'widgets_init', 't_em_widgets_init' );

/**
 * Add Bootstrap classes to navbar "li" items
 *
 * @since Twenty'em 1.2
 */
function t_em_nav_menu_css_class( $classes, $item, $args ){
	if ( $args->theme_location == 'footer-menu' ) :
		$classes[] = 'list-inline-item';
	elseif ( $args->theme_location == 'top-menu' || $args->theme_location == 'navigation-menu' ) :
		$classes[] = 'nav-item';
	endif;
	return $classes;
}
add_filter( 'nav_menu_css_class', 't_em_nav_menu_css_class', 10, 3 );

/**
 * Add Bootstrap classes to navbar "anchor" items
 *
 * @since Twenty'em 1.2
 */
function t_em_nav_menu_link_attributes( $attr, $item, $args ){
	if ( $args->theme_location == 'footer-menu' ) :
		$attr['class'] = '';
	elseif ( $args->theme_location == 'top-menu' || $args->theme_location == 'navigation-menu' ) :
		$attr['class'] = 'nav-link';
	endif;
	return $attr;
}
add_filter( 'nav_menu_link_attributes', 't_em_nav_menu_link_attributes', 10, 3 );

/**
 * Checks if individual pages supports comments
 *
 * @since Twenty'em 1.1.2
 */
function t_em_pages_supports_comments(){
	global $t_em;
	if ( ! $t_em['single_page_comments'] )
		remove_post_type_support( 'page', 'comments' );
}
add_action( 'init', 't_em_pages_supports_comments' );
?>
